using Tesy.Content;

namespace Tesy.Classes
{
    static internal class TimeZones
    {
        static public readonly Dictionary<string, TimeZoneContent> TimeZonesList = new() {
            {"1", new("CI,BF,GH,GM,GN,IS,ML,MR,SH,SL,SN,TG", "Africa/Abidjan", "Greenwich Standard Time", "(UTC\u002B00:00)", "")},
            {"2", new("DZ", "Africa/Algiers", "W. Central Africa Standard Time", "(UTC\u002B01:00)", "")},
            {"3", new("GW", "Africa/Bissau", "Greenwich Standard Time", "(UTC\u002B00:00)", "")},
            {"4", new("EG", "Africa/Cairo", "Egypt Standard Time", "(UTC\u002B02:00)", "")},
            {"5", new("MA", "Africa/Casablanca", "Morocco Standard Time", "(UTC\u002B01:00)", "")},
            {"6", new("ES", "Africa/Ceuta", "Romance Standard Time", "(UTC\u002B01:00)", "Ceuta, Melilla")},
            {"7", new("EH", "Africa/El_Aaiun", "Morocco Standard Time", "(UTC\u002B01:00)", "")},
            {"8", new("ZA,LS,SZ", "Africa/Johannesburg", "South Africa Standard Time", "(UTC\u002B02:00)", "")},
            {"9", new("SS", "Africa/Juba", "South Africa Standard Time", "(UTC\u002B02:00)", "")},
            {"10", new("SD", "Africa/Khartoum", "Sudan Standard Time", "(UTC\u002B02:00)", "")},
            {"11", new("NG,AO,BJ,CD,CF,CG,CM,GA,GQ,NE", "Africa/Lagos", "W. Central Africa Standard Time", "(UTC\u002B01:00)", "West Africa Time")},
            {"12", new("MZ,BI,BW,CD,MW,RW,ZM,ZW", "Africa/Maputo", "South Africa Standard Time", "(UTC\u002B02:00)", "Central Africa Time")},
            {"13", new("LR", "Africa/Monrovia", "Greenwich Standard Time", "(UTC\u002B00:00)", "")},
            {"14", new("KE,DJ,ER,ET,KM,MG,SO,TZ,UG,YT", "Africa/Nairobi", "E. Africa Standard Time", "(UTC\u002B03:00)", "")},
            {"15", new("TD", "Africa/Ndjamena", "W. Central Africa Standard Time", "(UTC\u002B01:00)", "")},
            {"16", new("ST", "Africa/Sao_Tome", "Sao Tome Standard Time", "(UTC\u002B00:00)", "")},
            {"17", new("LY", "Africa/Tripoli", "Libya Standard Time", "(UTC\u002B02:00)", "")},
            {"18", new("TN", "Africa/Tunis", "W. Central Africa Standard Time", "(UTC\u002B01:00)", "")},
            {"19", new("NA", "Africa/Windhoek", "Namibia Standard Time", "(UTC\u002B02:00)", "")},
            {"20", new("US", "America/Adak", "Aleutian Standard Time", "(UTC-10:00)", "Alaska - western Aleutians")},
            {"21", new("US", "America/Anchorage", "Alaskan Standard Time", "(UTC-09:00)", "Alaska (most areas)")},
            {"22", new("BR", "America/Araguaina", "Tocantins Standard Time", "(UTC-03:00)", "Tocantins")},
            {"23", new("AR", "America/Argentina/Buenos_Aires", "Argentina Standard Time", "(UTC-03:00)", "Buenos Aires (BA, CF)")},
            {"24", new("AR", "America/Argentina/Catamarca", "Argentina Standard Time", "(UTC-03:00)", "Catamarca (CT); Chubut (CH)")},
            {"25", new("AR", "America/Argentina/Cordoba", "Argentina Standard Time", "(UTC-03:00)", "most areas: CB, CC, CN, ER, FM, MN, SE, SF")},
            {"26", new("AR", "America/Argentina/Jujuy", "Argentina Standard Time", "(UTC-03:00)", "Jujuy (JY)")},
            {"27", new("AR", "America/Argentina/La_Rioja", "Argentina Standard Time", "(UTC-03:00)", "La Rioja (LR)")},
            {"28", new("AR", "America/Argentina/Mendoza", "Argentina Standard Time", "(UTC-03:00)", "Mendoza (MZ)")},
            {"29", new("AR", "America/Argentina/Rio_Gallegos", "Argentina Standard Time", "(UTC-03:00)", "Santa Cruz (SC)")},
            {"30", new("AR", "America/Argentina/Salta", "Argentina Standard Time", "(UTC-03:00)", "Salta (SA, LP, NQ, RN)")},
            {"31", new("AR", "America/Argentina/San_Juan", "Argentina Standard Time", "(UTC-03:00)", "San Juan (SJ)")},
            {"32", new("AR", "America/Argentina/San_Luis", "Argentina Standard Time", "(UTC-03:00)", "San Luis (SL)")},
            {"33", new("AR", "America/Argentina/Tucuman", "Argentina Standard Time", "(UTC-03:00)", "Tucum\u00E1n (TM)")},
            {"34", new("AR", "America/Argentina/Ushuaia", "Argentina Standard Time", "(UTC-03:00)", "Tierra del Fuego (TF)")},
            {"35", new("PY", "America/Asuncion", "Paraguay Standard Time", "(UTC-04:00)", "")},
            {"36", new("BR", "America/Bahia", "Bahia Standard Time", "(UTC-03:00)", "Bahia")},
            {"37", new("MX", "America/Bahia_Banderas", "Central Standard Time (Mexico)", "(UTC-06:00)", "Bah\u00EDa de Banderas")},
            {"38", new("BB", "America/Barbados", "SA Western Standard Time", "(UTC-04:00)", "")},
            {"39", new("BR", "America/Belem", "SA Eastern Standard Time", "(UTC-03:00)", "Par\u00E1 (east); Amap\u00E1")},
            {"40", new("BZ", "America/Belize", "Central America Standard Time", "(UTC-06:00)", "")},
            {"41", new("BR", "America/Boa_Vista", "SA Western Standard Time", "(UTC-04:00)", "Roraima")},
            {"42", new("CO", "America/Bogota", "SA Pacific Standard Time", "(UTC-05:00)", "")},
            {"43", new("US", "America/Boise", "Mountain Standard Time", "(UTC-07:00)", "Mountain - ID (south); OR (east)")},
            {"44", new("CA", "America/Cambridge_Bay", "Mountain Standard Time", "(UTC-07:00)", "Mountain - NU (west)")},
            {"45", new("BR", "America/Campo_Grande", "Central Brazilian Standard Time", "(UTC-04:00)", "Mato Grosso do Sul")},
            {"46", new("MX", "America/Cancun", "Eastern Standard Time (Mexico)", "(UTC-05:00)", "Quintana Roo")},
            {"47", new("VE", "America/Caracas", "Venezuela Standard Time", "(UTC-04:00)", "")},
            {"48", new("GF", "America/Cayenne", "SA Eastern Standard Time", "(UTC-03:00)", "")},
            {"49", new("US", "America/Chicago", "Central Standard Time", "(UTC-06:00)", "Central (most areas)")},
            {"50", new("MX", "America/Chihuahua", "Mountain Standard Time (Mexico)", "(UTC-07:00)", "Chihuahua (most areas)")},
            {"51", new("MX", "America/Ciudad_Juarez", null, "(UTC-07:00)", "Chihuahua (US border - west)")},
            {"52", new("CR", "America/Costa_Rica", "Central America Standard Time", "(UTC-06:00)", "")},
            {"53", new("BR", "America/Cuiaba", "Central Brazilian Standard Time", "(UTC-04:00)", "Mato Grosso")},
            {"54", new("GL", "America/Danmarkshavn", "Greenwich Standard Time", "(UTC\u002B00:00)", "National Park (east coast)")},
            {"55", new("CA", "America/Dawson", "Yukon Standard Time", "(UTC-07:00)", "MST - Yukon (west)")},
            {"56", new("CA", "America/Dawson_Creek", "US Mountain Standard Time", "(UTC-07:00)", "MST - BC (Dawson Cr, Ft St John)")},
            {"57", new("US", "America/Denver", "Mountain Standard Time", "(UTC-07:00)", "Mountain (most areas)")},
            {"58", new("US", "America/Detroit", "Eastern Standard Time", "(UTC-05:00)", "Eastern - MI (most areas)")},
            {"59", new("CA", "America/Edmonton", "Mountain Standard Time", "(UTC-07:00)", "Mountain - AB; BC (E); NT (E); SK (W)")},
            {"60", new("BR", "America/Eirunepe", "SA Pacific Standard Time", "(UTC-05:00)", "Amazonas (west)")},
            {"61", new("SV", "America/El_Salvador", "Central America Standard Time", "(UTC-06:00)", "")},
            {"62", new("CA", "America/Fort_Nelson", "US Mountain Standard Time", "(UTC-07:00)", "MST - BC (Ft Nelson)")},
            {"63", new("BR", "America/Fortaleza", "SA Eastern Standard Time", "(UTC-03:00)", "Brazil (northeast: MA, PI, CE, RN, PB)")},
            {"64", new("CA", "America/Glace_Bay", "Atlantic Standard Time", "(UTC-04:00)", "Atlantic - NS (Cape Breton)")},
            {"65", new("CA", "America/Goose_Bay", "Atlantic Standard Time", "(UTC-04:00)", "Atlantic - Labrador (most areas)")},
            {"66", new("TC", "America/Grand_Turk", "Turks And Caicos Standard Time", "(UTC-05:00)", "")},
            {"67", new("GT", "America/Guatemala", "Central America Standard Time", "(UTC-06:00)", "")},
            {"68", new("EC", "America/Guayaquil", "SA Pacific Standard Time", "(UTC-05:00)", "Ecuador (mainland)")},
            {"69", new("GY", "America/Guyana", "SA Western Standard Time", "(UTC-04:00)", "")},
            {"70", new("CA", "America/Halifax", "Atlantic Standard Time", "(UTC-04:00)", "Atlantic - NS (most areas); PE")},
            {"71", new("CU", "America/Havana", "Cuba Standard Time", "(UTC-05:00)", "")},
            {"72", new("MX", "America/Hermosillo", "US Mountain Standard Time", "(UTC-07:00)", "Sonora")},
            {"73", new("US", "America/Indiana/Indianapolis", "US Eastern Standard Time", "(UTC-05:00)", "Eastern - IN (most areas)")},
            {"74", new("US", "America/Indiana/Knox", "Central Standard Time", "(UTC-06:00)", "Central - IN (Starke)")},
            {"75", new("US", "America/Indiana/Marengo", "US Eastern Standard Time", "(UTC-05:00)", "Eastern - IN (Crawford)")},
            {"76", new("US", "America/Indiana/Petersburg", "Eastern Standard Time", "(UTC-05:00)", "Eastern - IN (Pike)")},
            {"77", new("US", "America/Indiana/Tell_City", "Central Standard Time", "(UTC-06:00)", "Central - IN (Perry)")},
            {"78", new("US", "America/Indiana/Vevay", "US Eastern Standard Time", "(UTC-05:00)", "Eastern - IN (Switzerland)")},
            {"79", new("US", "America/Indiana/Vincennes", "Eastern Standard Time", "(UTC-05:00)", "Eastern - IN (Da, Du, K, Mn)")},
            {"80", new("US", "America/Indiana/Winamac", "Eastern Standard Time", "(UTC-05:00)", "Eastern - IN (Pulaski)")},
            {"81", new("CA", "America/Inuvik", "Mountain Standard Time", "(UTC-07:00)", "Mountain - NT (west)")},
            {"82", new("CA", "America/Iqaluit", "Eastern Standard Time", "(UTC-05:00)", "Eastern - NU (most areas)")},
            {"83", new("JM", "America/Jamaica", "SA Pacific Standard Time", "(UTC-05:00)", "")},
            {"84", new("US", "America/Juneau", "Alaskan Standard Time", "(UTC-09:00)", "Alaska - Juneau area")},
            {"85", new("US", "America/Kentucky/Louisville", "Eastern Standard Time", "(UTC-05:00)", "Eastern - KY (Louisville area)")},
            {"86", new("US", "America/Kentucky/Monticello", "Eastern Standard Time", "(UTC-05:00)", "Eastern - KY (Wayne)")},
            {"87", new("BO", "America/La_Paz", "SA Western Standard Time", "(UTC-04:00)", "")},
            {"88", new("PE", "America/Lima", "SA Pacific Standard Time", "(UTC-05:00)", "")},
            {"89", new("US", "America/Los_Angeles", "Pacific Standard Time", "(UTC-08:00)", "Pacific")},
            {"90", new("BR", "America/Maceio", "SA Eastern Standard Time", "(UTC-03:00)", "Alagoas, Sergipe")},
            {"91", new("NI", "America/Managua", "Central America Standard Time", "(UTC-06:00)", "")},
            {"92", new("BR", "America/Manaus", "SA Western Standard Time", "(UTC-04:00)", "Amazonas (east)")},
            {"93", new("MQ", "America/Martinique", "SA Western Standard Time", "(UTC-04:00)", "")},
            {"94", new("MX", "America/Matamoros", "Central Standard Time", "(UTC-06:00)", "Coahuila, Nuevo Le\u00F3n, Tamaulipas (US border)")},
            {"95", new("MX", "America/Mazatlan", "Mountain Standard Time (Mexico)", "(UTC-07:00)", "Baja California Sur, Nayarit (most areas), Sinaloa")},
            {"96", new("US", "America/Menominee", "Central Standard Time", "(UTC-06:00)", "Central - MI (Wisconsin border)")},
            {"97", new("MX", "America/Merida", "Central Standard Time (Mexico)", "(UTC-06:00)", "Campeche, Yucat\u00E1n")},
            {"98", new("US", "America/Metlakatla", "Alaskan Standard Time", "(UTC-09:00)", "Alaska - Annette Island")},
            {"99", new("MX", "America/Mexico_City", "Central Standard Time (Mexico)", "(UTC-06:00)", "Central Mexico")},
            {"100", new("PM", "America/Miquelon", "Saint Pierre Standard Time", "(UTC-03:00)", "")},
            {"101", new("CA", "America/Moncton", "Atlantic Standard Time", "(UTC-04:00)", "Atlantic - New Brunswick")},
            {"102", new("MX", "America/Monterrey", "Central Standard Time (Mexico)", "(UTC-06:00)", "Durango; Coahuila, Nuevo Le\u00F3n, Tamaulipas (most areas)")},
            {"103", new("UY", "America/Montevideo", "Montevideo Standard Time", "(UTC-03:00)", "")},
            {"104", new("US", "America/New_York", "Eastern Standard Time", "(UTC-05:00)", "Eastern (most areas)")},
            {"105", new("US", "America/Nome", "Alaskan Standard Time", "(UTC-09:00)", "Alaska (west)")},
            {"106", new("BR", "America/Noronha", "UTC-02", "(UTC-02:00)", "Atlantic islands")},
            {"107", new("US", "America/North_Dakota/Beulah", "Central Standard Time", "(UTC-06:00)", "Central - ND (Mercer)")},
            {"108", new("US", "America/North_Dakota/Center", "Central Standard Time", "(UTC-06:00)", "Central - ND (Oliver)")},
            {"109", new("US", "America/North_Dakota/New_Salem", "Central Standard Time", "(UTC-06:00)", "Central - ND (Morton rural)")},
            {"110", new("GL", "America/Nuuk", "Greenland Standard Time", "(UTC-03:00)", "most of Greenland")},
            {"111", new("MX", "America/Ojinaga", "Mountain Standard Time", "(UTC-07:00)", "Chihuahua (US border - east)")},
            {"112", new("PA,CA,KY", "America/Panama", "SA Pacific Standard Time", "(UTC-05:00)", "EST - ON (Atikokan), NU (Coral H)")},
            {"113", new("SR", "America/Paramaribo", "SA Eastern Standard Time", "(UTC-03:00)", "")},
            {"114", new("US,CA", "America/Phoenix", "US Mountain Standard Time", "(UTC-07:00)", "MST - AZ (most areas), Creston BC")},
            {"115", new("HT", "America/Port-au-Prince", "Haiti Standard Time", "(UTC-05:00)", "")},
            {"116", new("BR", "America/Porto_Velho", "SA Western Standard Time", "(UTC-04:00)", "Rond\u00F4nia")},
            {"117", new("PR,AG,CA,AI,AW,BL,BQ,CW,DM,GD,GP,KN,LC,MF,MS,SX,TT,VC,VG,VI", "America/Puerto_Rico", "SA Western Standard Time", "(UTC-04:00)", "AST")},
            {"118", new("CL", "America/Punta_Arenas", "Magallanes Standard Time", "(UTC-03:00)", "Region of Magallanes")},
            {"119", new("CA", "America/Rankin_Inlet", "Central Standard Time", "(UTC-06:00)", "Central - NU (central)")},
            {"120", new("BR", "America/Recife", "SA Eastern Standard Time", "(UTC-03:00)", "Pernambuco")},
            {"121", new("CA", "America/Regina", "Canada Central Standard Time", "(UTC-06:00)", "CST - SK (most areas)")},
            {"122", new("CA", "America/Resolute", "Central Standard Time", "(UTC-06:00)", "Central - NU (Resolute)")},
            {"123", new("BR", "America/Rio_Branco", "SA Pacific Standard Time", "(UTC-05:00)", "Acre")},
            {"124", new("BR", "America/Santarem", "SA Eastern Standard Time", "(UTC-03:00)", "Par\u00E1 (west)")},
            {"125", new("CL", "America/Santiago", "Pacific SA Standard Time", "(UTC-04:00)", "most of Chile")},
            {"126", new("DO", "America/Santo_Domingo", "SA Western Standard Time", "(UTC-04:00)", "")},
            {"127", new("BR", "America/Sao_Paulo", "E. South America Standard Time", "(UTC-03:00)", "Brazil (southeast: GO, DF, MG, ES, RJ, SP, PR, SC, RS)")},
            {"128", new("GL", "America/Scoresbysund", "Azores Standard Time", "(UTC-01:00)", "Scoresbysund/Ittoqqortoormiit")},
            {"129", new("US", "America/Sitka", "Alaskan Standard Time", "(UTC-09:00)", "Alaska - Sitka area")},
            {"130", new("CA", "America/St_Johns", "Newfoundland Standard Time", "(UTC-03:30)", "Newfoundland; Labrador (southeast)")},
            {"131", new("CA", "America/Swift_Current", "Canada Central Standard Time", "(UTC-06:00)", "CST - SK (midwest)")},
            {"132", new("HN", "America/Tegucigalpa", "Central America Standard Time", "(UTC-06:00)", "")},
            {"133", new("GL", "America/Thule", "Atlantic Standard Time", "(UTC-04:00)", "Thule/Pituffik")},
            {"134", new("MX", "America/Tijuana", "Pacific Standard Time (Mexico)", "(UTC-08:00)", "Baja California")},
            {"135", new("CA,BS", "America/Toronto", "Eastern Standard Time", "(UTC-05:00)", "Eastern - ON, QC (most areas)")},
            {"136", new("CA", "America/Vancouver", "Pacific Standard Time", "(UTC-08:00)", "Pacific - BC (most areas)")},
            {"137", new("CA", "America/Whitehorse", "Yukon Standard Time", "(UTC-07:00)", "MST - Yukon (east)")},
            {"138", new("CA", "America/Winnipeg", "Central Standard Time", "(UTC-06:00)", "Central - ON (west); Manitoba")},
            {"139", new("US", "America/Yakutat", "Alaskan Standard Time", "(UTC-09:00)", "Alaska - Yakutat")},
            {"140", new("AQ", "Antarctica/Casey", "Central Pacific Standard Time", "(UTC\u002B11:00)", "Casey")},
            {"141", new("AQ", "Antarctica/Davis", "SE Asia Standard Time", "(UTC\u002B07:00)", "Davis")},
            {"142", new("AU", "Antarctica/Macquarie", "Tasmania Standard Time", "(UTC\u002B10:00)", "Macquarie Island")},
            {"143", new("AQ", "Antarctica/Mawson", "West Asia Standard Time", "(UTC\u002B05:00)", "Mawson")},
            {"144", new("AQ", "Antarctica/Palmer", "SA Eastern Standard Time", "(UTC-03:00)", "Palmer")},
            {"145", new("AQ", "Antarctica/Rothera", "SA Eastern Standard Time", "(UTC-03:00)", "Rothera")},
            {"146", new("AQ", "Antarctica/Troll", null, "(UTC-03:00)", "Troll")},
            {"147", new("KZ", "Asia/Almaty", "Central Asia Standard Time", "(UTC\u002B06:00)", "most of Kazakhstan")},
            {"148", new("JO", "Asia/Amman", "Jordan Standard Time", "(UTC\u002B03:00)", "")},
            {"149", new("RU", "Asia/Anadyr", "Russia Time Zone 11", "(UTC\u002B12:00)", "MSK\u002B09 - Bering Sea")},
            {"150", new("KZ", "Asia/Aqtau", "West Asia Standard Time", "(UTC\u002B05:00)", "Mangghysta\u016B/Mankistau")},
            {"151", new("KZ", "Asia/Aqtobe", "West Asia Standard Time", "(UTC\u002B05:00)", "Aqt\u00F6be/Aktobe")},
            {"152", new("TM", "Asia/Ashgabat", "West Asia Standard Time", "(UTC\u002B05:00)", "")},
            {"153", new("KZ", "Asia/Atyrau", "West Asia Standard Time", "(UTC\u002B05:00)", "Atyra\u016B/Atirau/Gur\u0027yev")},
            {"154", new("IQ", "Asia/Baghdad", "Arabic Standard Time", "(UTC\u002B03:00)", "")},
            {"155", new("AZ", "Asia/Baku", "Azerbaijan Standard Time", "(UTC\u002B04:00)", "")},
            {"156", new("TH,CX,KH,LA,VN", "Asia/Bangkok", "SE Asia Standard Time", "(UTC\u002B07:00)", "north Vietnam")},
            {"157", new("RU", "Asia/Barnaul", "Altai Standard Time", "(UTC\u002B07:00)", "MSK\u002B04 - Altai")},
            {"158", new("LB", "Asia/Beirut", "Middle East Standard Time", "(UTC\u002B02:00)", "")},
            {"159", new("KG", "Asia/Bishkek", "Central Asia Standard Time", "(UTC\u002B06:00)", "")},
            {"160", new("RU", "Asia/Chita", "Transbaikal Standard Time", "(UTC\u002B09:00)", "MSK\u002B06 - Zabaykalsky")},
            {"161", new("MN", "Asia/Choibalsan", "Ulaanbaatar Standard Time", "(UTC\u002B08:00)", "Dornod, S\u00FCkhbaatar")},
            {"162", new("LK", "Asia/Colombo", "Sri Lanka Standard Time", "(UTC\u002B05:30)", "")},
            {"163", new("SY", "Asia/Damascus", "Syria Standard Time", "(UTC\u002B02:00)", "")},
            {"164", new("BD", "Asia/Dhaka", "Bangladesh Standard Time", "(UTC\u002B06:00)", "")},
            {"165", new("TL", "Asia/Dili", "Tokyo Standard Time", "(UTC\u002B09:00)", "")},
            {"166", new("AE,OM,RE,SC,TF", "Asia/Dubai", "Arabian Standard Time", "(UTC\u002B04:00)", "Crozet, Scattered Is")},
            {"167", new("TJ", "Asia/Dushanbe", "West Asia Standard Time", "(UTC\u002B05:00)", "")},
            {"168", new("CY", "Asia/Famagusta", "GTB Standard Time", "(UTC\u002B02:00)", "Northern Cyprus")},
            {"169", new("PS", "Asia/Gaza", "West Bank Standard Time", "(UTC\u002B02:00)", "Gaza Strip")},
            {"170", new("PS", "Asia/Hebron", "West Bank Standard Time", "(UTC\u002B02:00)", "West Bank")},
            {"171", new("VN", "Asia/Ho_Chi_Minh", "SE Asia Standard Time", "(UTC\u002B07:00)", "south Vietnam")},
            {"172", new("HK", "Asia/Hong_Kong", "China Standard Time", "(UTC\u002B08:00)", "")},
            {"173", new("MN", "Asia/Hovd", "W. Mongolia Standard Time", "(UTC\u002B07:00)", "Bayan-\u00D6lgii, Govi-Altai, Hovd, Uvs, Zavkhan")},
            {"174", new("RU", "Asia/Irkutsk", "North Asia East Standard Time", "(UTC\u002B08:00)", "MSK\u002B05 - Irkutsk, Buryatia")},
            {"175", new("ID", "Asia/Jakarta", "SE Asia Standard Time", "(UTC\u002B07:00)", "Java, Sumatra")},
            {"176", new("ID", "Asia/Jayapura", "Tokyo Standard Time", "(UTC\u002B09:00)", "New Guinea (West Papua / Irian Jaya); Malukus/Moluccas")},
            {"177", new("IL", "Asia/Jerusalem", "Israel Standard Time", "(UTC\u002B02:00)", "")},
            {"178", new("AF", "Asia/Kabul", "Afghanistan Standard Time", "(UTC\u002B04:30)", "")},
            {"179", new("RU", "Asia/Kamchatka", "Russia Time Zone 11", "(UTC\u002B12:00)", "MSK\u002B09 - Kamchatka")},
            {"180", new("PK", "Asia/Karachi", "Pakistan Standard Time", "(UTC\u002B05:00)", "")},
            {"181", new("NP", "Asia/Kathmandu", "Nepal Standard Time", "(UTC\u002B05:45)", "")},
            {"182", new("RU", "Asia/Khandyga", "Yakutsk Standard Time", "(UTC\u002B09:00)", "MSK\u002B06 - Tomponsky, Ust-Maysky")},
            {"183", new("IN", "Asia/Kolkata", "India Standard Time", "(UTC\u002B05:30)", "")},
            {"184", new("RU", "Asia/Krasnoyarsk", "North Asia Standard Time", "(UTC\u002B07:00)", "MSK\u002B04 - Krasnoyarsk area")},
            {"185", new("MY,BN", "Asia/Kuching", "Singapore Standard Time", "(UTC\u002B08:00)", "Sabah, Sarawak")},
            {"186", new("MO", "Asia/Macau", "China Standard Time", "(UTC\u002B08:00)", "")},
            {"187", new("RU", "Asia/Magadan", "Magadan Standard Time", "(UTC\u002B11:00)", "MSK\u002B08 - Magadan")},
            {"188", new("ID", "Asia/Makassar", "Singapore Standard Time", "(UTC\u002B08:00)", "Borneo (east, south); Sulawesi/Celebes, Bali, Nusa Tengarra; Timor (west)")},
            {"189", new("PH", "Asia/Manila", "Singapore Standard Time", "(UTC\u002B08:00)", "")},
            {"190", new("CY", "Asia/Nicosia", "GTB Standard Time", "(UTC\u002B02:00)", "most of Cyprus")},
            {"191", new("RU", "Asia/Novokuznetsk", "North Asia Standard Time", "(UTC\u002B07:00)", "MSK\u002B04 - Kemerovo")},
            {"192", new("RU", "Asia/Novosibirsk", "N. Central Asia Standard Time", "(UTC\u002B07:00)", "MSK\u002B04 - Novosibirsk")},
            {"193", new("RU", "Asia/Omsk", "Omsk Standard Time", "(UTC\u002B06:00)", "MSK\u002B03 - Omsk")},
            {"194", new("KZ", "Asia/Oral", "West Asia Standard Time", "(UTC\u002B05:00)", "West Kazakhstan")},
            {"195", new("ID", "Asia/Pontianak", "SE Asia Standard Time", "(UTC\u002B07:00)", "Borneo (west, central)")},
            {"196", new("KP", "Asia/Pyongyang", "North Korea Standard Time", "(UTC\u002B09:00)", "")},
            {"197", new("QA,BH", "Asia/Qatar", "Arab Standard Time", "(UTC\u002B03:00)", "")},
            {"198", new("KZ", "Asia/Qostanay", "Central Asia Standard Time", "(UTC\u002B06:00)", "Qostanay/Kostanay/Kustanay")},
            {"199", new("KZ", "Asia/Qyzylorda", "Qyzylorda Standard Time", "(UTC\u002B05:00)", "Qyzylorda/Kyzylorda/Kzyl-Orda")},
            {"200", new("SA,AQ,KW,YE", "Asia/Riyadh", "Arab Standard Time", "(UTC\u002B03:00)", "Syowa")},
            {"201", new("RU", "Asia/Sakhalin", "Sakhalin Standard Time", "(UTC\u002B11:00)", "MSK\u002B08 - Sakhalin Island")},
            {"202", new("UZ", "Asia/Samarkand", "West Asia Standard Time", "(UTC\u002B05:00)", "Uzbekistan (west)")},
            {"203", new("KR", "Asia/Seoul", "Korea Standard Time", "(UTC\u002B09:00)", "")},
            {"204", new("CN", "Asia/Shanghai", "China Standard Time", "(UTC\u002B08:00)", "Beijing Time")},
            {"205", new("SG,MY", "Asia/Singapore", "Singapore Standard Time", "(UTC\u002B08:00)", "peninsular Malaysia")},
            {"206", new("RU", "Asia/Srednekolymsk", "Russia Time Zone 10", "(UTC\u002B11:00)", "MSK\u002B08 - Sakha (E); N Kuril Is")},
            {"207", new("TW", "Asia/Taipei", "Taipei Standard Time", "(UTC\u002B08:00)", "")},
            {"208", new("UZ", "Asia/Tashkent", "West Asia Standard Time", "(UTC\u002B05:00)", "Uzbekistan (east)")},
            {"209", new("GE", "Asia/Tbilisi", "Georgian Standard Time", "(UTC\u002B04:00)", "")},
            {"210", new("IR", "Asia/Tehran", "Iran Standard Time", "(UTC\u002B03:30)", "")},
            {"211", new("BT", "Asia/Thimphu", "Bangladesh Standard Time", "(UTC\u002B06:00)", "")},
            {"212", new("JP", "Asia/Tokyo", "Tokyo Standard Time", "(UTC\u002B09:00)", "")},
            {"213", new("RU", "Asia/Tomsk", "Tomsk Standard Time", "(UTC\u002B07:00)", "MSK\u002B04 - Tomsk")},
            {"214", new("MN", "Asia/Ulaanbaatar", "Ulaanbaatar Standard Time", "(UTC\u002B08:00)", "most of Mongolia")},
            {"215", new("CN,AQ", "Asia/Urumqi", null, "(UTC\u002B08:00)", "Xinjiang Time, Vostok")},
            {"216", new("RU", "Asia/Ust-Nera", "Vladivostok Standard Time", "(UTC\u002B10:00)", "MSK\u002B07 - Oymyakonsky")},
            {"217", new("RU", "Asia/Vladivostok", "Vladivostok Standard Time", "(UTC\u002B10:00)", "MSK\u002B07 - Amur River")},
            {"218", new("RU", "Asia/Yakutsk", "Yakutsk Standard Time", "(UTC\u002B09:00)", "MSK\u002B06 - Lena River")},
            {"219", new("MM,CC", "Asia/Yangon", "Myanmar Standard Time", "(UTC\u002B06:30)", "")},
            {"220", new("RU", "Asia/Yekaterinburg", "Ekaterinburg Standard Time", "(UTC\u002B05:00)", "MSK\u002B02 - Urals")},
            {"221", new("AM", "Asia/Yerevan", "Caucasus Standard Time", "(UTC\u002B04:00)", "")},
            {"222", new("PT", "Atlantic/Azores", "Azores Standard Time", "(UTC-01:00)", "Azores")},
            {"223", new("BM", "Atlantic/Bermuda", "Atlantic Standard Time", "(UTC-04:00)", "")},
            {"224", new("ES", "Atlantic/Canary", "GMT Standard Time", "(UTC\u002B00:00)", "Canary Islands")},
            {"225", new("CV", "Atlantic/Cape_Verde", "Cape Verde Standard Time", "(UTC-01:00)", "")},
            {"226", new("FO", "Atlantic/Faroe", "GMT Standard Time", "(UTC\u002B00:00)", "")},
            {"227", new("PT", "Atlantic/Madeira", "GMT Standard Time", "(UTC\u002B00:00)", "Madeira Islands")},
            {"228", new("GS", "Atlantic/South_Georgia", "UTC-02", "(UTC-02:00)", "")},
            {"229", new("FK", "Atlantic/Stanley", "SA Eastern Standard Time", "(UTC-03:00)", "")},
            {"230", new("AU", "Australia/Adelaide", "Cen. Australia Standard Time", "(UTC\u002B09:30)", "South Australia")},
            {"231", new("AU", "Australia/Brisbane", "E. Australia Standard Time", "(UTC\u002B10:00)", "Queensland (most areas)")},
            {"232", new("AU", "Australia/Broken_Hill", "Cen. Australia Standard Time", "(UTC\u002B09:30)", "New South Wales (Yancowinna)")},
            {"233", new("AU", "Australia/Darwin", "AUS Central Standard Time", "(UTC\u002B09:30)", "Northern Territory")},
            {"234", new("AU", "Australia/Eucla", "Aus Central W. Standard Time", "(UTC\u002B08:45)", "Western Australia (Eucla)")},
            {"235", new("AU", "Australia/Hobart", "Tasmania Standard Time", "(UTC\u002B10:00)", "Tasmania")},
            {"236", new("AU", "Australia/Lindeman", "E. Australia Standard Time", "(UTC\u002B10:00)", "Queensland (Whitsunday Islands)")},
            {"237", new("AU", "Australia/Lord_Howe", "Lord Howe Standard Time", "(UTC\u002B10:30)", "Lord Howe Island")},
            {"238", new("AU", "Australia/Melbourne", "AUS Eastern Standard Time", "(UTC\u002B10:00)", "Victoria")},
            {"239", new("AU", "Australia/Perth", "W. Australia Standard Time", "(UTC\u002B08:00)", "Western Australia (most areas)")},
            {"240", new("AU", "Australia/Sydney", "AUS Eastern Standard Time", "(UTC\u002B10:00)", "New South Wales (most areas)")},
            {"241", new("AD", "Europe/Andorra", "W. Europe Standard Time", "(UTC\u002B01:00)", "")},
            {"242", new("RU", "Europe/Astrakhan", "Astrakhan Standard Time", "(UTC\u002B04:00)", "MSK\u002B01 - Astrakhan")},
            {"243", new("GR", "Europe/Athens", "GTB Standard Time", "(UTC\u002B02:00)", "")},
            {"244", new("RS,BA,HR,ME,MK,SI", "Europe/Belgrade", "Central Europe Standard Time", "(UTC\u002B01:00)", "")},
            {"245", new("DE,DK,NO,SE,SJ", "Europe/Berlin", "W. Europe Standard Time", "(UTC\u002B01:00)", "most of Germany")},
            {"246", new("BE,LU,NL", "Europe/Brussels", "Romance Standard Time", "(UTC\u002B01:00)", "")},
            {"247", new("RO", "Europe/Bucharest", "GTB Standard Time", "(UTC\u002B02:00)", "")},
            {"248", new("HU", "Europe/Budapest", "Central Europe Standard Time", "(UTC\u002B01:00)", "")},
            {"249", new("MD", "Europe/Chisinau", "E. Europe Standard Time", "(UTC\u002B02:00)", "")},
            {"250", new("IE", "Europe/Dublin", "GMT Standard Time", "(UTC\u002B00:00)", "")},
            {"251", new("GI", "Europe/Gibraltar", "W. Europe Standard Time", "(UTC\u002B01:00)", "")},
            {"252", new("FI,AX", "Europe/Helsinki", "FLE Standard Time", "(UTC\u002B02:00)", "")},
            {"253", new("TR", "Europe/Istanbul", "Turkey Standard Time", "(UTC\u002B03:00)", "")},
            {"254", new("RU", "Europe/Kaliningrad", "Kaliningrad Standard Time", "(UTC\u002B02:00)", "MSK-01 - Kaliningrad")},
            {"255", new("UA", "Europe/Kiev", "FLE Standard Time", "(UTC\u002B02:00)", "most of Ukraine")},
            {"256", new("RU", "Europe/Kirov", "Russian Standard Time", "(UTC\u002B03:00)", "MSK\u002B00 - Kirov")},
            {"257", new("PT", "Europe/Lisbon", "GMT Standard Time", "(UTC\u002B00:00)", "Portugal (mainland)")},
            {"258", new("GB,GG,IM,JE", "Europe/London", "GMT Standard Time", "(UTC\u002B00:00)", "")},
            {"259", new("ES", "Europe/Madrid", "Romance Standard Time", "(UTC\u002B01:00)", "Spain (mainland)")},
            {"260", new("MT", "Europe/Malta", "W. Europe Standard Time", "(UTC\u002B01:00)", "")},
            {"261", new("BY", "Europe/Minsk", "Belarus Standard Time", "(UTC\u002B03:00)", "")},
            {"262", new("RU", "Europe/Moscow", "Russian Standard Time", "(UTC\u002B03:00)", "MSK\u002B00 - Moscow area")},
            {"263", new("FR,MC", "Europe/Paris", "Romance Standard Time", "(UTC\u002B01:00)", "")},
            {"264", new("CZ,SK", "Europe/Prague", "Central Europe Standard Time", "(UTC\u002B01:00)", "")},
            {"265", new("LV", "Europe/Riga", "FLE Standard Time", "(UTC\u002B02:00)", "")},
            {"266", new("IT,SM,VA", "Europe/Rome", "W. Europe Standard Time", "(UTC\u002B01:00)", "")},
            {"267", new("RU", "Europe/Samara", "Russia Time Zone 3", "(UTC\u002B04:00)", "MSK\u002B01 - Samara, Udmurtia")},
            {"268", new("RU", "Europe/Saratov", "Saratov Standard Time", "(UTC\u002B04:00)", "MSK\u002B01 - Saratov")},
            {"269", new("RU,UA", "Europe/Simferopol", "Russian Standard Time", "(UTC\u002B03:00)", "Crimea")},
            {"270", new("BG", "Europe/Sofia", "FLE Standard Time", "(UTC\u002B02:00)", "")},
            {"271", new("EE", "Europe/Tallinn", "FLE Standard Time", "(UTC\u002B02:00)", "")},
            {"272", new("AL", "Europe/Tirane", "Central Europe Standard Time", "(UTC\u002B01:00)", "")},
            {"273", new("RU", "Europe/Ulyanovsk", "Astrakhan Standard Time", "(UTC\u002B04:00)", "MSK\u002B01 - Ulyanovsk")},
            {"274", new("AT", "Europe/Vienna", "W. Europe Standard Time", "(UTC\u002B01:00)", "")},
            {"275", new("LT", "Europe/Vilnius", "FLE Standard Time", "(UTC\u002B02:00)", "")},
            {"276", new("RU", "Europe/Volgograd", "Volgograd Standard Time", "(UTC\u002B03:00)", "MSK\u002B00 - Volgograd")},
            {"277", new("PL", "Europe/Warsaw", "Central European Standard Time", "(UTC\u002B01:00)", "")},
            {"278", new("CH,DE,LI", "Europe/Zurich", "W. Europe Standard Time", "(UTC\u002B01:00)", "B\u00FCsingen")},
            {"279", new("IO", "Indian/Chagos", "Central Asia Standard Time", "(UTC\u002B06:00)", "")},
            {"280", new("MV,TF", "Indian/Maldives", "West Asia Standard Time", "(UTC\u002B05:00)", "Kerguelen, St Paul I, Amsterdam I")},
            {"281", new("MU", "Indian/Mauritius", "Mauritius Standard Time", "(UTC\u002B04:00)", "")},
            {"282", new("WS", "Pacific/Apia", "Samoa Standard Time", "(UTC\u002B13:00)", "")},
            {"283", new("NZ,AQ", "Pacific/Auckland", "New Zealand Standard Time", "(UTC\u002B12:00)", "New Zealand time")},
            {"284", new("PG", "Pacific/Bougainville", "Bougainville Standard Time", "(UTC\u002B11:00)", "Bougainville")},
            {"285", new("NZ", "Pacific/Chatham", "Chatham Islands Standard Time", "(UTC\u002B12:45)", "Chatham Islands")},
            {"286", new("CL", "Pacific/Easter", "Easter Island Standard Time", "(UTC-06:00)", "Easter Island")},
            {"287", new("VU", "Pacific/Efate", "Central Pacific Standard Time", "(UTC\u002B11:00)", "")},
            {"288", new("TK", "Pacific/Fakaofo", "UTC\u002B13", "(UTC\u002B13:00)", "")},
            {"289", new("FJ", "Pacific/Fiji", "Fiji Standard Time", "(UTC\u002B12:00)", "")},
            {"290", new("EC", "Pacific/Galapagos", "Central America Standard Time", "(UTC-06:00)", "Gal\u00E1pagos Islands")},
            {"291", new("PF", "Pacific/Gambier", "UTC-09", "(UTC-09:00)", "Gambier Islands")},
            {"292", new("SB,FM", "Pacific/Guadalcanal", "Central Pacific Standard Time", "(UTC\u002B11:00)", "Pohnpei")},
            {"293", new("GU,MP", "Pacific/Guam", "West Pacific Standard Time", "(UTC\u002B10:00)", "")},
            {"294", new("US", "Pacific/Honolulu", "Hawaiian Standard Time", "(UTC-10:00)", "Hawaii")},
            {"295", new("KI", "Pacific/Kanton", null, "(UTC-10:00)", "Phoenix Islands")},
            {"296", new("KI", "Pacific/Kiritimati", "Line Islands Standard Time", "(UTC\u002B14:00)", "Line Islands")},
            {"297", new("FM", "Pacific/Kosrae", "Central Pacific Standard Time", "(UTC\u002B11:00)", "Kosrae")},
            {"298", new("MH", "Pacific/Kwajalein", "UTC\u002B12", "(UTC\u002B12:00)", "Kwajalein")},
            {"299", new("PF", "Pacific/Marquesas", "Marquesas Standard Time", "(UTC-09:30)", "Marquesas Islands")},
            {"300", new("NR", "Pacific/Nauru", "UTC\u002B12", "(UTC\u002B12:00)", "")},
            {"301", new("NU", "Pacific/Niue", "UTC-11", "(UTC-11:00)", "")},
            {"302", new("NF", "Pacific/Norfolk", "Norfolk Standard Time", "(UTC\u002B11:00)", "")},
            {"303", new("NC", "Pacific/Noumea", "Central Pacific Standard Time", "(UTC\u002B11:00)", "")},
            {"304", new("AS,UM", "Pacific/Pago_Pago", "UTC-11", "(UTC-11:00)", "Midway")},
            {"305", new("PW", "Pacific/Palau", "Tokyo Standard Time", "(UTC\u002B09:00)", "")},
            {"306", new("PN", "Pacific/Pitcairn", "UTC-08", "(UTC-08:00)", "")},
            {"307", new("PG,AQ,FM", "Pacific/Port_Moresby", "West Pacific Standard Time", "(UTC\u002B10:00)", "Papua New Guinea (most areas), Chuuk, Yap, Dumont d\u0027Urville")},
            {"308", new("CK", "Pacific/Rarotonga", "Hawaiian Standard Time", "(UTC-10:00)", "")},
            {"309", new("PF", "Pacific/Tahiti", "Hawaiian Standard Time", "(UTC-10:00)", "Society Islands")},
            {"310", new("KI,MH,TV,UM,WF", "Pacific/Tarawa", "UTC\u002B12", "(UTC\u002B12:00)", "Gilberts, Marshalls, Wake")},
            {"311", new("TO", "Pacific/Tongatapu", "Tonga Standard Time", "(UTC\u002B13:00)", "")}
        };
    }
}